name: Update Value Workflow

on:
  push:
    branches:
      - main

jobs:
  update-value:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set initial value
        run: echo "0" >> initial_value.txt

      - name: Read initial value
        id: read_initial
        run: echo "MY_VALUE=$(cat initial_value.txt)" >> "$GITHUB_ENV"

      - name: Perform calculation
        id: calculate
        run: updated_value = echo "NEW_VALUE=$(($MY_VALUE + 10))" 

      - name: Update value
        id: update_value
        run: echo "$(updated_value)" > initial_value.txt

      - name: Display updated value
        run: cat initial_value.txt
